import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { headers, cookies } from 'next/headers'
import { createClient } from '@/lib/utils/supabase/server'
import { UserProvider } from '@/lib/context/UserContext'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient()
  const { data: { user }, error } = await supabase.auth.getUser()

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider initialUser={user}>
          {children}
          <Toaster />
        </UserProvider>
      </body>
    </html>
  );
}
