// Generated by ts-to-zod
import { z } from "zod";
import { Json } from "./database.types";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const applicationsRowSchema = z.object({
  approved_at: z.string().nullable(),
  created_at: z.string(),
  group_user_id: z.string(),
  id: z.string(),
  rejected_at: z.string().nullable(),
  status: z.string(),
  tier_id: z.string(),
  updated_at: z.string(),
});

export const applicationsInsertSchema = z.object({
  approved_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  group_user_id: z.string(),
  id: z.string().optional(),
  rejected_at: z.string().optional().nullable(),
  status: z.string().optional(),
  tier_id: z.string(),
  updated_at: z.string().optional(),
});

export const applicationsUpdateSchema = z.object({
  approved_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  group_user_id: z.string().optional(),
  id: z.string().optional(),
  rejected_at: z.string().optional().nullable(),
  status: z.string().optional(),
  tier_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const applicationsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("applications_group_user_id_fkey"),
    columns: z.tuple([z.literal("group_user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("applications_tier_id_fkey"),
    columns: z.tuple([z.literal("tier_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("membership_tier"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const groupRowSchema = z.object({
  alternate_name: z.string().nullable(),
  created_at: z.string(),
  created_by: z.string(),
  description: z.string().nullable(),
  id: z.string(),
  name: z.string(),
  parent_id: z.string().nullable(),
  slug: z.string(),
  type: z.string().nullable(),
});

export const groupInsertSchema = z.object({
  alternate_name: z.string().optional().nullable(),
  created_at: z.string().optional(),
  created_by: z.string(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string(),
  parent_id: z.string().optional().nullable(),
  slug: z.string(),
  type: z.string().optional().nullable(),
});

export const groupUpdateSchema = z.object({
  alternate_name: z.string().optional().nullable(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional(),
  parent_id: z.string().optional().nullable(),
  slug: z.string().optional(),
  type: z.string().optional().nullable(),
});

export const groupRelationshipsSchema = z.tuple([]);

export const groupRoleTypeSchema = z.union([
  z.literal("GUEST"),
  z.literal("MEMBER"),
]);

export const groupRolesInsertSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  group_id: z.string().optional().nullable(),
  id: z.string().optional(),
  permissions: z.array(z.string()).optional().nullable(),
  role_name: z.string().optional().nullable(),
  type: groupRoleTypeSchema.optional().nullable(),
});

export const groupRolesUpdateSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  group_id: z.string().optional().nullable(),
  id: z.string().optional(),
  permissions: z.array(z.string()).optional().nullable(),
  role_name: z.string().optional().nullable(),
  type: groupRoleTypeSchema.optional().nullable(),
});

export const groupRolesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("public_group_roles_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const groupUsersRowSchema = z.object({
  created_at: z.string(),
  group_id: z.string(),
  id: z.string(),
  is_active: z.boolean(),
  updated_at: z.string(),
  user_id: z.string(),
});

export const groupUsersInsertSchema = z.object({
  created_at: z.string().optional(),
  group_id: z.string(),
  id: z.string().optional(),
  is_active: z.boolean().optional(),
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const groupUsersUpdateSchema = z.object({
  created_at: z.string().optional(),
  group_id: z.string().optional(),
  id: z.string().optional(),
  is_active: z.boolean().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const groupUsersRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("group_users_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const memberIdsRowSchema = z.object({
  created_at: z.string(),
  group_user_id: z.string(),
  id: z.string(),
  member_id: z.string(),
  updated_at: z.string(),
});

export const memberIdsInsertSchema = z.object({
  created_at: z.string().optional(),
  group_user_id: z.string(),
  id: z.string().optional(),
  member_id: z.string(),
  updated_at: z.string().optional(),
});

export const memberIdsUpdateSchema = z.object({
  created_at: z.string().optional(),
  group_user_id: z.string().optional(),
  id: z.string().optional(),
  member_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const memberIdsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("member_ids_group_user_id_fkey"),
    columns: z.tuple([z.literal("group_user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const membershipRoleRowSchema = z.object({
  created_at: z.string(),
  group_role_id: z.string(),
  id: z.string(),
  membership_id: z.string(),
});

export const membershipRoleInsertSchema = z.object({
  created_at: z.string().optional(),
  group_role_id: z.string(),
  id: z.string().optional(),
  membership_id: z.string(),
});

export const membershipRoleUpdateSchema = z.object({
  created_at: z.string().optional(),
  group_role_id: z.string().optional(),
  id: z.string().optional(),
  membership_id: z.string().optional(),
});

export const membershipRoleRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("membership_role_group_role_id_fkey"),
    columns: z.tuple([z.literal("group_role_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group_roles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const membershipTierRowSchema = z.object({
  activation_type: z.string(),
  created_at: z.string(),
  description: z.string().nullable(),
  group_id: z.string(),
  id: z.string(),
  name: z.string(),
  price: z.number(),
  updated_at: z.string(),
});

export const membershipTierInsertSchema = z.object({
  activation_type: z.string().optional(),
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  group_id: z.string(),
  id: z.string().optional(),
  name: z.string(),
  price: z.number(),
  updated_at: z.string().optional(),
});

export const membershipTierUpdateSchema = z.object({
  activation_type: z.string().optional(),
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  group_id: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  price: z.number().optional(),
  updated_at: z.string().optional(),
});

export const membershipTierRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("membership_tier_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const membershipsRowSchema = z.object({
  created_at: z.string(),
  end_date: z.string().nullable(),
  group_user_id: z.string(),
  id: z.string(),
  is_active: z.boolean(),
  start_date: z.string(),
  tier_id: z.string(),
  updated_at: z.string(),
});

export const membershipsInsertSchema = z.object({
  created_at: z.string().optional(),
  end_date: z.string().optional().nullable(),
  group_user_id: z.string(),
  id: z.string().optional(),
  is_active: z.boolean().optional(),
  start_date: z.string(),
  tier_id: z.string(),
  updated_at: z.string().optional(),
});

export const membershipsUpdateSchema = z.object({
  created_at: z.string().optional(),
  end_date: z.string().optional().nullable(),
  group_user_id: z.string().optional(),
  id: z.string().optional(),
  is_active: z.boolean().optional(),
  start_date: z.string().optional(),
  tier_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const membershipsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("memberships_group_user_id_fkey"),
    columns: z.tuple([z.literal("group_user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("memberships_tier_id_fkey"),
    columns: z.tuple([z.literal("tier_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("membership_tier"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const profilesRowSchema = z.object({
  avatar_url: z.string().nullable(),
  first_name: z.string().nullable(),
  id: z.string(),
  last_name: z.string().nullable(),
  updated_at: z.string().nullable(),
  username: z.string().nullable(),
});

export const profilesInsertSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  first_name: z.string().optional().nullable(),
  id: z.string(),
  last_name: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  username: z.string().optional().nullable(),
});

export const profilesUpdateSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  first_name: z.string().optional().nullable(),
  id: z.string().optional(),
  last_name: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  username: z.string().optional().nullable(),
});

export const profilesRelationshipsSchema = z.tuple([]);

export const appPermissionSchema = z.union([
  z.literal("group.edit"),
  z.literal("group.delete"),
  z.literal("group.members.invite"),
  z.literal("group.members.approve"),
]);

export const rolePermissionsInsertSchema = z.object({
  id: z.number().optional(),
  permission: appPermissionSchema,
  role_id: z.string(),
});

export const rolePermissionsUpdateSchema = z.object({
  id: z.number().optional(),
  permission: appPermissionSchema.optional(),
  role_id: z.string().optional(),
});

export const rolePermissionsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("public_role_permissions_role_id_fkey"),
    columns: z.tuple([z.literal("role_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group_roles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const userRolesRowSchema = z.object({
  created_at: z.string(),
  group_role_id: z.string(),
  id: z.string(),
  is_active: z.boolean().nullable(),
  user_id: z.string(),
});

export const userRolesInsertSchema = z.object({
  created_at: z.string().optional(),
  group_role_id: z.string(),
  id: z.string().optional(),
  is_active: z.boolean().optional().nullable(),
  user_id: z.string(),
});

export const userRolesUpdateSchema = z.object({
  created_at: z.string().optional(),
  group_role_id: z.string().optional(),
  id: z.string().optional(),
  is_active: z.boolean().optional().nullable(),
  user_id: z.string().optional(),
});

export const userRolesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("public_user_roles_group_role_id_fkey"),
    columns: z.tuple([z.literal("group_role_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group_roles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("public_user_roles_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const applicationsViewRowSchema = z.object({
  approved_at: z.string().nullable(),
  created_at: z.string().nullable(),
  group_id: z.string().nullable(),
  id: z.string().nullable(),
  is_active: z.boolean().nullable(),
  rejected_at: z.string().nullable(),
  tier_data: jsonSchema.nullable(),
  tier_id: z.string().nullable(),
  user_data: jsonSchema.nullable(),
  user_id: z.string().nullable(),
});

export const applicationsViewRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("applications_tier_id_fkey"),
    columns: z.tuple([z.literal("tier_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("membership_tier"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_users_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("group"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const membershipActivationTypeSchema = z.union([
  z.literal("automatic"),
  z.literal("review_required"),
  z.literal("payment_required"),
  z.literal("review_then_payment"),
]);

export const groupRolesRowSchema = z.object({
  created_at: z.string(),
  created_by: z.string().nullable(),
  description: z.string().nullable(),
  group_id: z.string().nullable(),
  id: z.string(),
  permissions: z.array(z.string()).nullable(),
  role_name: z.string().nullable(),
  type: groupRoleTypeSchema.nullable(),
});

export const rolePermissionsRowSchema = z.object({
  id: z.number(),
  permission: appPermissionSchema,
  role_id: z.string(),
});
